# Generated by Django 5.0.3 on 2024-03-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_alter_infouser_options_infouser_age_infouser_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ваше полное имя')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('number', models.CharField(max_length=50, verbose_name='Ваш номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваша эл.почта')),
            ],
            options={
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
