# Generated by Django 5.0.3 on 2024-03-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog1', models.ImageField(upload_to='', verbose_name='Ваш первый блог')),
                ('data1', models.DateField()),
                ('description1', models.CharField(max_length=255, verbose_name='Описание')),
                ('blog2', models.ImageField(upload_to='', verbose_name='Ваш первый блог')),
                ('data2', models.DateField()),
                ('description2', models.CharField(max_length=255, verbose_name='Описание')),
                ('blog3', models.ImageField(upload_to='', verbose_name='Ваш первый блог')),
                ('data3', models.DateField()),
                ('description3', models.CharField(max_length=255, verbose_name='Описание')),
                ('blog4', models.ImageField(upload_to='', verbose_name='Ваш первый блог')),
                ('data4', models.DateField()),
                ('description4', models.CharField(max_length=255, verbose_name='Описание')),
                ('blog5', models.ImageField(upload_to='', verbose_name='Ваш первый блог')),
                ('data5', models.DateField()),
                ('description5', models.CharField(max_length=255, verbose_name='Описание')),
                ('blog6', models.ImageField(upload_to='', verbose_name='Ваш первый блог')),
                ('data6', models.DateField()),
                ('description6', models.CharField(max_length=255, verbose_name='Описание')),
            ],
        ),
    ]
