# Generated by Django 5.0.3 on 2024-03-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog4',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog5',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog6',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='data4',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='data5',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='data6',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='description5',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='description6',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog2',
            field=models.ImageField(upload_to='', verbose_name='Ваш второй блог'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog3',
            field=models.ImageField(upload_to='', verbose_name='Ваш третий блог'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='data1',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='data2',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='data3',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
