# Generated by Django 5.0.3 on 2024-03-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Информация о пользователя', 'verbose_name_plural': 'Информация о пользователей'},
        ),
        migrations.AddField(
            model_name='infouser',
            name='age',
            field=models.IntegerField(default=1, verbose_name='Ваш возраст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='country',
            field=models.CharField(default=1, max_length=50, verbose_name='Ваша страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Ваша эл.почта'),
            preserve_default=False,
        ),
    ]
