# Generated by Django 5.0.3 on 2024-03-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience1', models.CharField(max_length=255, verbose_name='Кем вы работали')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('work_company', models.CharField(max_length=255, verbose_name='В какой компании вы работали')),
            ],
            options={
                'verbose_name_plural': 'Опыт работы',
            },
        ),
    ]
