# Generated by Django 5.0.3 on 2024-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_remove_blogs_blog4_remove_blogs_blog5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('about', models.CharField(max_length=255, verbose_name='О вас')),
                ('email', models.CharField(max_length=50, verbose_name='Эл.почта')),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
