# Generated by Django 5.0.3 on 2024-03-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_portfolio_alter_blogs_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_skils', models.CharField(max_length=255, verbose_name='Какими языками вы владеете')),
            ],
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Портфолио'},
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog2',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog3',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='data2',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='data3',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='description3',
        ),
        migrations.AddField(
            model_name='infouser',
            name='facebook',
            field=models.URLField(default=1, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='instagram',
            field=models.URLField(default=1, verbose_name='Instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='telegram',
            field=models.URLField(default=1, verbose_name='Telegram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='whatsapp',
            field=models.URLField(default=1, verbose_name='Whatsapp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='youtube',
            field=models.URLField(default=1, verbose_name='YouTube'),
            preserve_default=False,
        ),
    ]
