# Generated by Django 5.0.3 on 2024-03-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_skills_alter_portfolio_options_remove_blogs_blog2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Portfolio', verbose_name='Image')),
                ('data', models.DateField(verbose_name='Date')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('place', models.CharField(max_length=30, verbose_name='Place')),
                ('year', models.CharField(max_length=255, verbose_name='Year')),
                ('subtitle', models.CharField(max_length=255, verbose_name='SubTitle')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.URLField(verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Testimonialers', verbose_name='Testimonialer image')),
                ('fullname', models.CharField(max_length=255, verbose_name='Testimonialer fullname')),
                ('job', models.CharField(max_length=70, verbose_name='Testimonialer job')),
                ('testimonial', models.TextField(verbose_name='Testimonialer testimonial')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='user name')),
                ('lastname', models.CharField(max_length=255, verbose_name='user surname')),
                ('phone_number', models.CharField(max_length=25, verbose_name='user phone number')),
                ('job', models.CharField(max_length=255, verbose_name='user job')),
                ('image', models.ImageField(upload_to='UserInfo', verbose_name='user image')),
                ('description', models.TextField(verbose_name='user description')),
                ('age', models.IntegerField(verbose_name='user age')),
                ('email', models.EmailField(max_length=254, verbose_name='user email')),
                ('address', models.CharField(max_length=255, verbose_name='user address')),
                ('location', models.CharField(max_length=255, verbose_name='user location')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('linkedin', models.URLField(verbose_name='Linkedin')),
                ('github', models.URLField(verbose_name='Github')),
                ('instagram', models.URLField(verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'User admin',
                'verbose_name_plural': 'Users admin',
            },
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='InfoUser',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolioes'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience1',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='work_company',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='about',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='email',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='your_skils',
        ),
        migrations.AddField(
            model_name='experience',
            name='place',
            field=models.CharField(default=1, max_length=30, verbose_name='Place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='subtitle',
            field=models.CharField(default=1, max_length=255, verbose_name='SubTitle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='year',
            field=models.CharField(default=1, max_length=255, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='choosing',
            field=models.CharField(default=1, max_length=50, verbose_name='photos/design/brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default=1, upload_to='Portfolio', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default=1, max_length=150, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='lang',
            field=models.CharField(default=1, max_length=50, verbose_name='Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='percent',
            field=models.IntegerField(default=1, verbose_name='Percent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skills',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
