# Generated by Django 5.0.3 on 2024-03-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_blog_educations_office_service_testimonials_userinfo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='educations',
            options={'verbose_name_plural': 'Образовние'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name_plural': 'Опыты'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name_plural': 'Oффисы'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Знания'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'Aдминистратор пользователей'},
        ),
        migrations.RemoveField(
            model_name='skills',
            name='percent',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='Portfolio', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='place',
            field=models.CharField(max_length=30, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='year',
            field=models.CharField(max_length=255, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='place',
            field=models.CharField(max_length=30, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='Субтитры'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.CharField(max_length=255, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='office',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='office',
            name='image',
            field=models.URLField(verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='choosing',
            field=models.CharField(max_length=50, verbose_name='Фото Дизайн Брэнд'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='Portfolio', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='lang',
            field=models.CharField(max_length=50, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Эл.почта'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(upload_to='UserInfo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(max_length=255, verbose_name='Ваша работа'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Фамилие'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(max_length=25, verbose_name='Номер'),
        ),
    ]
